### ISSUE TITLE
PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by tarekrached** [philschatz/react-octicons#3]
`warning.js:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

New release version of React (15.5.0) add new Warning that React.PropTypes will be deprecated soon. You need to use the `prop-types` package from npm instead.

**Comment by philschatz** [comment]
Fixed in #4
